
services:
  postgres:
    image: postgres:15
    container_name: proshooter_postgres
    environment:
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: angel
      POSTGRES_DB: proshooter_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # Scripts de inicializaci√≥n
    networks:
      - proshooter_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U angel -d proshooter_db_dev"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: proshooter_api
    environment:
      ENV: dev
      DB_PORT: 5432
      API_PORT: 8000
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: angel
      POSTGRES_DB: proshooter_db_dev
      BUILD_TARGET: development
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      SECRET_KEY: n83iPiObXhiauePC3IVbDeTlj8uTzPTd
      DATABASE_URL: postgresql://angel:angel@postgres:5432/proshooter_db_dev

    ports:
      - "3000:8000"
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - proshooter_network
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  proshooter_network:
    driver: bridge

volumes:
  postgres_data:
