
services:
  postgres:
    image: subkey/proshooter-db:latest
    container_name: proshooter_bd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U angel -d proshooter_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: angel
      POSTGRES_DB: proshooter_db
    networks:
      - proshooter-network


  api:
    container_name: proshooter_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./logs:/app/logs  # Volumen adicional para logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - proshooter-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    # En desarrollo, usamos restart: unless-stopped en lugar de always
    # para evitar ciclos infinitos de reinicio durante el desarrollo
    restart: unless-stopped

    # Separamos los comandos de migración e inicio
    # Para desarrollo (ambiente por defecto)
    command: >
      bash -c "
        # Ejecutamos migraciones
        alembic upgrade head &&
        # Iniciamos el servidor
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "

    # Perfil para producción
    # profiles:
    #   - production
    # En producción, comentaríamos la sección command anterior y
    # descomentaríamos esta para usar una configuración más estable
    # command: >
    #   bash -c "
    #     alembic upgrade head &&
    #     uvicorn src.main:app --host 0.0.0.0 --port 8000
    #   "

networks:
  proshooter-network:
    driver: bridge

volumes:
  postgres_data:
  # Volumen para los logs si decides implementarlo
  # logs:
