services:
  postgres:
    image: postgres:14-alpine
    container_name: proshooter_bd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U angel -d proshooter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: angel
      POSTGRES_DB: proshooter_db
    networks:
      - proshooter-network

  api:
    container_name: proshooter_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    # environment:
    #   - DATABASE_URL=postgresql://angel:angel@postgres:5432/proshooter_db
    #   - SECRET_KEY=fasdfjasfsdfkasjdfoiadbasdbasd
    networks:
      - proshooter-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
    command: >
      bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  proshooter-network:
    driver: bridge

volumes:
  postgres_data:
