services:
  postgres:
    image: subkey/proshooter-db:latest
    container_name: proshooter_postgres_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - proshooter_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: proshooter-api:prod
    container_name: proshooter_api_prod
    environment:
      ENV: ${ENV}
      DB_PORT: ${DB_PORT}
      API_PORT: ${API_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_SENDER_EMAIL: ${RESEND_SENDER_EMAIL}
      RESET_TOKEN_EXPIRE_MINUTES: ${RESET_TOKEN_EXPIRE_MINUTES}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - proshooter_network_prod
    restart: unless-stopped
    command: >
      sh -c "
      echo 'Esperando a PostgreSQL...' &&
      while ! nc -z postgres 5432; do
        sleep 0.5;
      done;
      echo 'PostgreSQL está lista. Ejecutando migraciones...' &&
      alembic upgrade head &&
      echo 'Iniciando Uvicorn en modo producción' &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data_prod:

networks:
  proshooter_network_prod:
    driver: bridge
